### ISSUE TITLE
Issue while using langgraph.checkpoint.sqlite import SqliteSaver

### ISSUE THREAD

**Issue by jinooos** [langchain-ai/langgraph#2042]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
langgraph                   0.2.19
langgraph-checkpoint        1.0.9
langgraph-checkpoint-sqlite 1.0.3

from langgraph.checkpoint.sqlite import SqliteSaver
memory = SqliteSaver.from_conn_string(":memory:")
```

### Error Message and Stack Trace (if applicable)

```shell
AttributeError: '_GeneratorContextManager' object has no attribute 'get_next_version'
```

### Description

while using MemorySaver the code is working fine. Getting this error while trying to update this to SQLlite. 
from langgraph.checkpoint.memory import MemorySaver
memory = MemorySaver()

changed to 
from langgraph.checkpoint.sqlite import SqliteSaver
memory = SqliteSaver.from_conn_string(":memory:")

### System Info

langgraph==0.2.19
langgraph-checkpoint==1.0.9
langgraph-checkpoint-sqlite==1.0.3

**Comment by hinthornw** [comment]
Per the [docs](https://langchain-ai.github.io/langgraph/reference/checkpoints/#langgraph.checkpoint.sqlite.SqliteSaver.from_conn_string)
```
from langgraph.checkpoint.sqlite import SqliteSaver
with SqliteSaver.from_conn_string(":memory:") as memory:
    ...
```

**Comment by primeplanet** [comment]
Hi, I'm encountering the exact same error as described in this issue:

AttributeError: '_GeneratorContextManager' object has no attribute 'get_next_version'
This happens when using SqliteSaver initialized directly via SqliteSaver.from_conn_string(...) and passed to graph.compile(checkpointer=...). Like the original reporter, switching to MemorySaver resolves this specific error.

My Environment Details:

langgraph: 0.3.27
langgraph-checkpoint-sqlite: 2.0.6
Python: 3.13
Minimal Reproducible Example:

I was able to reproduce this consistently using the following minimal script:

Python
# test_checkpointer_minimal.py

import logging
import os
import sys
from pathlib import Path
from typing import TypedDict, Annotated, Sequence
import operator
import uuid
import sqlite3 # Import standard library

# --- Configure Basic Logging ---
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# --- LangGraph Imports ---
try:
    from langgraph.graph import StateGraph, END
    from langgraph.checkpoint.sqlite import SqliteSaver
except ImportError as e:
    logger.error(f"Failed to import LangGraph components: {e}")
    logger.error("Please ensure LangGraph is installed correctly in your environment.")
    sys.exit(1)

# --- Minimal State Definition ---
class MinimalState(TypedDict):
    counter: int
    messages: Annotated[Sequence[tuple], operator.add]

# --- Simple Node Functions ---
def node_a(state: MinimalState):
    logger.info("--- Entering Node A ---")
    count = state.get("counter", 0) + 1
    messages = state.get("messages", []) + [("system", f"Node A incremented counter to {count}")]
    logger.info(f"Node A: Counter = {count}")
    return {"counter": count, "messages": messages}

def node_b(state: MinimalState):
    logger.info("--- Entering Node B ---")
    count = state.get("counter", 0) + 1
    messages = state.get("messages", []) + [("system", f"Node B incremented counter to {count}")]
    logger.info(f"Node B: Counter = {count}")
    return {"counter": count, "messages": messages}

# --- Build the Graph ---
logger.info("Building minimal graph...")
workflow_builder = StateGraph(MinimalState)
workflow_builder.add_node("node_a", node_a)
workflow_builder.add_node("node_b", node_b)
workflow_builder.set_entry_point("node_a")
workflow_builder.add_edge("node_a", "node_b")
workflow_builder.add_edge("node_b", END)
logger.info("Graph structure defined.")

# --- Checkpointer Setup (Standard Method) ---
checkpoint_file = "./minimal_test_checkpoint.sqlite"
if os.path.exists(checkpoint_file):
    logger.warning(f"Deleting existing checkpoint file: {checkpoint_file}")
    os.remove(checkpoint_file)

logger.info(f"Initializing SqliteSaver with file: {checkpoint_file}")
try:
    # Initialize WITHOUT 'with' - Standard pattern for compile()
    memory = SqliteSaver.from_conn_string(checkpoint_file)
    logger.info("SqliteSaver initialized.")
except Exception as e:
    logger.error(f"Failed to initialize SqliteSaver: {e}", exc_info=True)
    sys.exit(1)

# --- Compile the Graph with Checkpointer ---
logger.info("Compiling graph with checkpointer...")
try:
    graph = workflow_builder.compile(checkpointer=memory)
    logger.info("Graph compiled successfully.")
except Exception as e:
    logger.error(f"Failed to compile graph: {e}", exc_info=True)
    sys.exit(1)

# --- Run the Graph Stream ---
thread_id = f"minimal-test-{uuid.uuid4()}"
config = {"configurable": {"thread_id": thread_id}}
initial_input = {"counter": 0, "messages": [("system", "Start")]}

logger.info(f"Running graph stream with thread_id: {thread_id}")
try:
    for i, step_output in enumerate(graph.stream(initial_input, config=config, stream_mode="updates")):
        latest_node_name = list(step_output.keys())[-1]
        logger.info(f"--- Stream Update {i+1} ---")
        logger.info(f"Node: {latest_node_name}")
        logger.info(f"State Update: {step_output[latest_node_name]}")

    logger.info("--- Graph stream finished successfully! ---")

except AttributeError as ae:
    if "'_GeneratorContextManager' object has no attribute 'get_next_version'" in str(ae):
         logger.error("!!! CAUGHT EXPECTED ERROR !!!")
         logger.error(f"AttributeError: {ae}", exc_info=True) # Log full traceback
    else:
         logger.error(f"Caught an unexpected AttributeError: {ae}", exc_info=True)
except Exception as e:
    logger.error(f"An unexpected error occurred during graph stream: {e}", exc_info=True)

finally:
    if 'memory' in locals() and hasattr(memory, 'conn') and memory.conn:
        try:
            memory.conn.close()
            logger.info("Closed checkpointer DB connection.")
        except Exception as e_close:
             logger.error(f"Error closing DB connection: {e_close}")
    logger.info("Minimal test script finished.")
Traceback from Minimal Example:

# Paste the full traceback you got when running the minimal script here
Traceback (most recent call last):
  File "/Users/mrud/Documents/agentic/debug_langgraph.py", line 95, in <module>
    for i, step_output in enumerate(graph.stream(initial_input, config=config, stream_mode="updates")):
                          ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/agentic/lib/python3.13/site-packages/langgraph/pregel/__init__.py", line 2289, in stream
    with SyncPregelLoop(
         ~~~~~~~~~~~~~~^
        input,
        ^^^^^^
    ...<17 lines>...
        migrate_checkpoint=self._migrate_checkpoint,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) as loop:
    ^
  File "/opt/anaconda3/envs/agentic/lib/python3.13/site-packages/langgraph/pregel/loop.py", line 984, in __init__
    self.checkpointer_get_next_version = checkpointer.get_next_version
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_GeneratorContextManager' object has no attribute 'get_next_version'
Regarding the with Statement Workaround:

[Link to the original issue comment if applicable] suggested using SqliteSaver as a context manager (with SqliteSaver.from_conn_string(...) as memory:). While this might avoid the AttributeError during initialization/compilation, it doesn't work for the standard graph execution workflow.

When compiling the graph inside the with block, like this:

Python
with SqliteSaver.from_conn_string("...") as memory:
    graph = workflow_builder.compile(checkpointer=memory)
# 'with' block ends here, closing the DB connection
The database connection is closed when the with block exits. Later attempts to run graph.stream(...) fail with sqlite3.ProgrammingError: Cannot operate on a closed database. because the checkpointer instance held by the compiled graph has a closed connection.

It seems the standard method of passing a SqliteSaver instance to compile() has an issue in these versions/environment where it's incorrectly treated as a context manager internally during the stream() call.

Hoping this information helps track down the root cause. Thanks!
