### ISSUE TITLE
How to use the ReAct agent from langchain with langgraph?

### ISSUE THREAD

**Issue by DanielProkhorov** [langchain-ai/langgraph#55]
Please add an example of ReAct agent (https://python.langchain.com/docs/modules/agents/agent_types/react) usage together with the langgraph framework.

I tried to combine them like so:

```
# Construct the ReAct agent

my_input = "some example utterance"

agent = create_react_agent(llm, tools, react_template_base)

agent_executer = create_agent_executor(agent, tools)

inputs = {"messages": [HumanMessage(content=my_input)]}

for output in agent_executer.stream(inputs):
    # stream() yields dictionaries with output keyed by node name
    for key, value in output.items():
        print(f"Output from node '{key}':")
        print("---")
        print(value)
    print("\n---\n")
```

but this doesn't work as expected.

**Comment by rwaneyvin** [comment]
from langchain import hub
from langchain.agents import Tool, create_react_agent

from langchain_google_genai import ChatGoogleGenerativeAI,GoogleGenerativeAI

import os

os.environ["SERPER_API_KEY"] = ""

from langchain_community.utilities import GoogleSerperAPIWrapper
search = GoogleSerperAPIWrapper()

tools = [
    Tool(
        name = "Search",
        func=search.run,
        description="useful for when you need to answer questions about current events",
    ),

]

prompt = hub.pull("hwchase17/react")


llm = ChatGoogleGenerativeAI(model="gemini-pro",
                        google_api_key="",
                        convert_system_message_to_human = True,
                        verbose = True,
                            )

agent_runnable = create_react_agent(llm, tools, prompt)





from typing import TypedDict, Annotated, List, Union
from langchain_core.agents import AgentAction, AgentFinish
from langchain_core.messages import BaseMessage
import operator
from typing import TypedDict, Annotated, Sequence


class AgentState(TypedDict):
   # The input string
   input: str
   # The list of previous messages in the conversation
   chat_history: list[BaseMessage]
   # The outcome of a given call to the agent
   # Needs `None` as a valid type, since this is what this will start as
   agent_outcome: Union[AgentAction, AgentFinish, None]
   return_direct: bool
   # List of actions and corresponding observations
   # Here we annotate this with `operator.add` to indicate that operations to
   # this state should be ADDED to the existing values (not overwrite it)
   intermediate_steps: Annotated[list[tuple[AgentAction, str]], operator.add]


from langchain_core.agents import AgentFinish
from langgraph.prebuilt.tool_executor import ToolExecutor


tool_executor = ToolExecutor(tools)


from langchain_core.agents import AgentActionMessageLog



# Define the agent
def run_agent(state):
    """
    inputs = state.copy()
    if len(inputs['intermediate_steps']) > 5:
        inputs['intermediate_steps'] = inputs['intermediate_steps'][-5:]
    """
    agent_outcome = agent_runnable.invoke(state)
    return {"agent_outcome": agent_outcome}



from langgraph.prebuilt import ToolInvocation

def execute_tools(state):

    messages = [state['agent_outcome'] ]
    last_message = messages[-1]
    ######### HUMAN input y/n ###########    
    # Get the most recent agent_outcome - this is the key added in the `agent` above
    # state_action = state['agent_outcome']
    # human_key = input(f"[y/n] continue with: {state_action}?")
    # if human_key == "n":
    #     raise ValueError
    
    tool_name = last_message.tool
    arguments = last_message
    # if tool_name == "tavily_search_results_json":
    if tool_name == "Search":
        
        if "return_direct" in arguments:
            del arguments["return_direct"]
    action = ToolInvocation(
        tool=tool_name,
        tool_input= last_message.tool_input,
    )
    # We call the tool_executor and get back a response
    response = tool_executor.invoke(action)
    return {"intermediate_steps": [(state['agent_outcome'],response)]}

# Define logic that will be used to determine which conditional edge to go down# 
    
def should_continue(state):

    messages = [state['agent_outcome'] ] 
    last_message = messages[-1]
    if "Action" not in last_message.log:
        return "end"
    # Otherwise if there is, we check if it's suppose to return direct
    else:
        arguments = state["return_direct"]
        if arguments is True:
            return "final"
        else:
            return "continue"
        

def first_agent(inputs):
    action = AgentActionMessageLog(
      # We force call this tool
      tool="Search",
      # We just pass in the `input` key to this tool
      tool_input=inputs["input"],
      log="",
      message_log=[]
    )
    return {"agent_outcome": action}


from langgraph.graph import END, StateGraph


# Define a new graph
workflow = StateGraph(AgentState)

# Define the two nodes we will cycle between
workflow.add_node("agent", run_agent)
workflow.add_node("action", execute_tools)
workflow.add_node("final", execute_tools)
# workflow.add_node("first_agent", first_agent)

# Set the entrypoint as `agent`
# This means that this node is the first one called
workflow.set_entry_point("agent")
# workflow.set_entry_point("first_agent")

# We now add a conditional edge
workflow.add_conditional_edges(
    # First, we define the start node. We use `agent`.
    # This means these are the edges taken after the `agent` node is called.
    "agent",
    # Next, we pass in the function that will determine which node is called next.
    should_continue,
    # Finally we pass in a mapping.
    # The keys are strings, and the values are other nodes.
    # END is a special node marking that the graph should finish.
    # What will happen is we will call `should_continue`, and then the output of that
    # will be matched against the keys in this mapping.
    # Based on which one it matches, that node will then be called.
    {
        # If `tools`, then we call the tool node.
        "continue": "action",
         # Final call
        "final": "final",
        # Otherwise we finish.
        "end": END
    }
)

# We now add a normal edge from `tools` to `agent`.
# This means that after `tools` is called, `agent` node is called next.
workflow.add_edge('action', 'agent')
workflow.add_edge('final', END)
# workflow.add_edge('first_agent', 'action')

# Finally, we compile it!
# This compiles it into a LangChain Runnable,
# meaning you can use it as you would any other runnable
app = workflow.compile()

inputs = {"input": "what is the weather in Taipei", "chat_history": [],"return_direct": False}

for s in app.stream(inputs):
    print(list(s.values())[0])
    print("----")

**Comment by rwaneyvin** [comment]
by the way, demo was uploaded to github FYI! 
[langgraph_demo](https://github.com/roboticsocialism/langgraph_demo)

**Comment by DanielProkhorov** [comment]
Thanks @rwaneyvin

**Comment by Kirushikesh** [comment]
@rwaneyvin one small question, ig the tools passed with the react agent should have one argument right. Does the react agent work for tools with multiple input?

**Comment by rwaneyvin** [comment]
> @rwaneyvin one small question, ig the tools passed with the react agent should have one argument right. Does the react agent work for tools with multiple input?

I'm not sure but do you mean tools in create_react_agent(llm, tools, prompt)?
tools could be a list of many tools, and then agent will first think and then pick one of the tool to solve its current job repeatly till agent achieve its goal.
theorically, you just give it a reasonable prompt, and the agent will try if possible.

**Comment by jasgeo75** [comment]
@rwaneyvin

I believe what he meant was that `create_react_agent` doesn't appear to work with functions that require more than a single input (parameter). So, the example below would not work because it has two parameters: `a` and `b`.

```python
@tool
async def amultiply(a: int, b: int) -> int:
    """Multiply two numbers."""
    return a * b
```

Is there a way to make this work?

**Comment by Kirushikesh** [comment]
@jasgeo75 @rwaneyvin  yes i meant this, if you have fn as a tools and if the function accepts multiple arguments, do we have a way to achieve the fn calling with react structure.

**Comment by jasgeo75** [comment]
I hadn't any luck getting `create_react_agent` to work as we've discussed (well, sort of - you need to write a custom output parser and use `render_text_description_and_args` as the tools_renderer, but it was unreliable).  I did have luck with the approach below which gets you ReAct with support for multiple inputs.

```python
from langchain import hub
from langchain.agents import AgentExecutor
from langchain.agents.format_scratchpad import format_log_to_str
from langchain.agents.output_parsers import JSONAgentOutputParser
from langchain.tools.render import render_text_description_and_args

prompt = hub.pull("hwchase17/react-multi-input-json") 
prompt = prompt.partial(
    tools=render_text_description_and_args(tools),
    tool_names=", ".join([t.name for t in tools]),
)

agent = (
    {
        "input": lambda x: x["input"],
        "agent_scratchpad": lambda x: format_log_to_str(x["intermediate_steps"]),
    }
    | prompt
    | llm_with_stop
    | JSONAgentOutputParser()
)
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)
```

**Comment by ikharsha** [comment]
now langgrapgh provides prebuilt react agent directly-:https://langchain-ai.github.io/langgraph/how-tos/create-react-agent/

**Comment by gmrukwa** [comment]
> now langgraph provides prebuilt react agent directly-:https://langchain-ai.github.io/langgraph/how-tos/create-react-agent/

For all the confused people around there: this actually isn't a ReAct agent. It's just some agent that uses tools, but it definitely doesn't follow the ReAct framework.

**Comment by vbarda** [comment]
@gmrukwa we added an explanation around this to the conceptual guides https://langchain-ai.github.io/langgraph/concepts/agentic_concepts/#react-implementation

**Comment by Fujiry0** [comment]
To understand an agent's thought process and utilize it for improving prompt engineering, I aim to extract the "thoughts" of a ReAct agent. However, if the agent of langchain does not adhere to the ReAct framework, would it be challenging to extract these thoughts?
