### ISSUE TITLE
Stream Chat LLM Token By Token is not working

### ISSUE THREAD

**Issue by ahmedmoorsy** [langchain-ai/langgraph#78]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

I am using the code in this notebook:
https://github.com/langchain-ai/langgraph/blob/main/examples/streaming-tokens.ipynb

streaming code:
```
from langchain_core.messages import HumanMessage
inputs = [HumanMessage(content="what is the weather in sf")]
async for event in app.astream_events(inputs, version="v1"):
    kind = event["event"]
    if kind == "on_chat_model_stream":
        content = event["data"]["chunk"].content
        if content:
            # Empty content in the context of OpenAI means
            # that the model is asking for a tool to be invoked.
            # So we only print non-empty content
            print(content, end="|")
    elif kind == "on_tool_start":
        print("--")
        print(
            f"Starting tool: {event['name']} with inputs: {event['data'].get('input')}"
        )
    elif kind == "on_tool_end":
        print(f"Done tool: {event['name']}")
        print(f"Tool output was: {event['data'].get('output')}")
        print("--")
```

### Error Message and Stack Trace (if applicable)

the streaming is not working, I am not receiving any output from this part:
```
    if kind == "on_chat_model_stream":
        content = event["data"]["chunk"].content
        if content:
            # Empty content in the context of OpenAI means
            # that the model is asking for a tool to be invoked.
            # So we only print non-empty content
            print(content, end="|")
```

### Description

the streaming is not working, I am not receiving any output

### System Info

langchain==0.1.5
langchain-community==0.0.17
langchain-core==0.1.18
langchain-openai==0.0.5
langgraph==0.0.21

**Comment by ahmedmoorsy** [comment]
@elliottshort So, what LangChain version do you recommend? with LangGraph `0.0.21`

**Comment by SavvasMohito** [comment]
Hey @ahmedmoorsy, which python version are you using? I had a similar issue when running on python 3.10 but the streaming worked once I upgraded to 3.12 (3.11 should also work, I think).

**Comment by SavvasMohito** [comment]
Nice one @tgram-3D. Does streaming follow-up questions work for you? I can get responses streamed in my initial prompt but when I perform a second question, it never returns anything. It's not that I am not capturing it, it seems like langgraph never exits the model invocation loop.

**Comment by tgram-3D** [comment]
@SavvasMohito I've just been playing around with the example streaming-tokens notebook with astream_events, and follow up questions seem to work fine using the node modifications described above. The notebook isn't really set up for memory though since all it does is add a single HumanMessage for each streaming event:

```
from langchain_core.messages import HumanMessage
inputs = [HumanMessage(content="what is the weather in sf")]
async for event in app.astream_events(inputs, version="v1"):
...
```
The way I'm currently using it for follow up questions is pretty basic:

```
class GraphConversation:
    def __init__(self, graph):
        self.graph = graph
        self.messages = []
        
    async def stream_conversation(self, question):
        self.messages.append(HumanMessage(content=question))
        async for event in app.astream_events(self.messages, version="v1"):
            kind = event["event"]
            if kind == "on_chat_model_stream":
                content = event["data"]["chunk"].content
                if content:
                    # Empty content in the context of OpenAI means
                    # that the model is asking for a tool to be invoked.
                    # So we only print non-empty content
                    print(content, end="|")
            elif kind == "on_tool_start":
                print("--")
                print(
                    f"Starting tool: {event['name']} with inputs: {event['data'].get('input')}"
                )
            elif kind == "on_tool_end":
                print(f"Done tool: {event['name']}")
                print(f"Tool output was: {event['data'].get('output')}")
                print("--")
    
```
`graph_convo = GraphConversation(graph=app)`

`await graph_convo.stream_conversation('what is the weather in sf')`

```
--
Starting tool: tavily_search_results_json with inputs: {'query': 'weather in San Francisco'}
Done tool: tavily_search_results_json
Tool output was: [{'url': 'https://www.marinij.com/2024/02/05/high-winds-heavy-rains-hit-the-bay-area/', 'content': '— San José Fire Dept. (@SJFD) February 5, 2024  Weather | Atmospheric river storm to soak Bay Area this weekend, with major flood danger in Southern California  Crystal Oudit said the forecast will start to improve on Monday, though Bay Area residents should expect more rain.  Weather Weather | High winds, heavy rains hit the Bay Area and the rest of California’s coast(Karl Mondon/Bay Area News Group) Waves crash over a breakwater in Alameda, Calif., with the San Francisco skyline in the background on Sunday, Feb. 4, 2024. High winds and heavy rainfall are ...'}]
--
The| weather| in| San| Francisco| is| currently| experiencing| high| winds| and| heavy| rains|.| You| can| find| more| information| about| the| weather| in| San| Francisco| [|here|](|https|://|www|.m|arin|ij|.com|/|202|4|/|02|/|05|/high|-w|inds|-heavy|-r|ains|-hit|-the|-b|ay|-area|/|).|
```
`await graph_convo.stream_conversation('what was the last question I asked you')`
`The| last| question| you| asked| me| was| "|what| is| the| weather| in| SF|?"|`

I'm sure there's a better way to do this sort of thing. Check out the new Persistence notebook. I currently cannot get astream_events to work with the persistence config at all though:

```
from langgraph.checkpoint.sqlite import SqliteSaver
memory = SqliteSaver.from_conn_string(":memory:")
app = workflow.compile(checkpointer=memory)

```
I tried this and got zero output, same deal without the configurable:

 `async for event in app.astream_events(inputs, {"configurable": {"thread_id": "2"}}, version="v1"):`

I'm sure there's a way to combine the two features, but the simple class method should work fine for frontend integration with websockets, etc.

**Comment by dmitryrPlanner5D** [comment]
I was struggling with tokens streaming in [this tutorial](https://github.com/langchain-ai/langgraph/blob/main/examples/streaming-tokens.ipynb). And I have found another workaround to enable streaming. I just added extra parameter `config` to my call_model function and pass it to the llm invoke:

```
# Define the function that calls the model
async def call_model(messages, config):
    response = await model.ainvoke(messages, config=config)
    # We return a list, because this will get added to the existing list
    return response
 ```
 
 That way I was able to fetch tokens stream from llm.

**Comment by simonrmonk** [comment]
Not clear on how, but [dmitryrPlanner5D](https://github.com/dmitryrPlanner5D)'s comment solved this for me too

**Comment by OSS-GR** [comment]
What are you guys passing in the config?

**Comment by dmitryrPlanner5D** [comment]
@OSS-GR 
I do not call function call_model myself, so I do not pass config there explicitly
My function call_model is called by langgraph and langgraph passes some config to it.
I do not control this config

**Comment by usersina** [comment]
Streaming is also not working if I update the [agent_supervisor notebook](https://github.com/langchain-ai/langgraph/blob/main/examples/multi_agent/agent_supervisor.ipynb) as specified in the documention (set `streaming` to True and make the tool calls `async`).

The `operator.add` in the `AgentState`'s `messages` is making it so that the final output from the supervisor has duplicated tokens, if I got it correctly. For example, here's the log from a slightly tweaked version of the notebook. In this example, the supervisor should output `MongoDBAgent` but it's outputting `MongoMongoDBMongoDBAgent`, resulting in a `KeyError`.

>{'op': 'replace', 'path': '', 'value': {'id': '1e88305f-e06c-4f9f-8120-20208defbb88', 'streamed_output': [], 'final_output': None, 'logs': {}, 'name': 'LangGraph', 'type': 'chain'}}
{'op': 'add', 'path': '/logs/ChatOpenAI', 'value': {'id': '69000165-10d9-4828-962d-653e95bbc436', 'name': 'ChatOpenAI', 'type': 'llm', 'tags': ['seq:step:2'], 'metadata': {}, 'start_time': '2024-04-23T13:54:01.044+00:00', 'streamed_output': [], 'streamed_output_str': [], 'final_output': None, 'end_time': None}}
{'op': 'add', 'path': '/logs/ChatOpenAI/streamed_output_str/-', 'value': ''}
{'op': 'add', 'path': '/logs/ChatOpenAI/streamed_output/-', 'value': AIMessageChunk(content='', additional_kwargs={'function_call': {'arguments': '', 'name': 'route'}})}
{'op': 'add', 'path': '/logs/ChatOpenAI/streamed_output_str/-', 'value': ''}
{'op': 'add', 'path': '/logs/ChatOpenAI/streamed_output/-', 'value': AIMessageChunk(content='', additional_kwargs={'function_call': {'arguments': '{"', 'name': ''}})}
{'op': 'add', 'path': '/logs/ChatOpenAI/streamed_output_str/-', 'value': ''}
{'op': 'add', 'path': '/logs/ChatOpenAI/streamed_output/-', 'value': AIMessageChunk(content='', additional_kwargs={'function_call': {'arguments': 'next', 'name': ''}})}
{'op': 'add', 'path': '/logs/ChatOpenAI/streamed_output_str/-', 'value': ''}
{'op': 'add', 'path': '/logs/ChatOpenAI/streamed_output/-', 'value': AIMessageChunk(content='', additional_kwargs={'function_call': {'arguments': '":"', 'name': ''}})}
{'op': 'add', 'path': '/logs/ChatOpenAI/streamed_output_str/-', 'value': ''}
{'op': 'add', 'path': '/logs/ChatOpenAI/streamed_output/-', 'value': AIMessageChunk(content='', additional_kwargs={'function_call': {'arguments': 'Mongo', 'name': ''}})}
{'op': 'add', 'path': '/logs/ChatOpenAI/streamed_output_str/-', 'value': ''}
{'op': 'add', 'path': '/logs/ChatOpenAI/streamed_output/-', 'value': AIMessageChunk(content='', additional_kwargs={'function_call': {'arguments': 'DB', 'name': ''}})}
{'op': 'add', 'path': '/logs/ChatOpenAI/streamed_output_str/-', 'value': ''}
{'op': 'add', 'path': '/logs/ChatOpenAI/streamed_output/-', 'value': AIMessageChunk(content='', additional_kwargs={'function_call': {'arguments': 'Agent', 'name': ''}})}
{'op': 'add', 'path': '/logs/ChatOpenAI/streamed_output_str/-', 'value': ''}
{'op': 'add', 'path': '/logs/ChatOpenAI/streamed_output/-', 'value': AIMessageChunk(content='', additional_kwargs={'function_call': {'arguments': '"}', 'name': ''}})}
{'op': 'add', 'path': '/logs/ChatOpenAI/streamed_output_str/-', 'value': ''}
{'op': 'add', 'path': '/logs/ChatOpenAI/streamed_output/-', 'value': AIMessageChunk(content='')}
{'op': 'add', 'path': '/logs/ChatOpenAI/final_output', 'value': {'generations': [[{'text': '', 'generation_info': {'finish_reason': 'stop'}, 'type': 'ChatGenerationChunk', 'message': AIMessageChunk(content='', additional_kwargs={'function_call': {'arguments': '{"next":"MongoDBAgent"}', 'name': 'route'}}, response_metadata={'finish_reason': 'stop'}, id='run-69000165-10d9-4828-962d-653e95bbc436')}]], 'llm_output': None, 'run': None}}
{'op': 'add', 'path': '/logs/ChatOpenAI/end_time', 'value': '2024-04-23T13:54:02.193+00:00'}
{'op': 'add', 'path': '/streamed_output/-', 'value': {'Supervisor': {'next': 'MongoMongoDBMongoDBAgent'}}}
{'op': 'replace', 'path': '/final_output', 'value': {'Supervisor': {'next': 'MongoMongoDBMongoDBAgent'}}}

**Comment by usersina** [comment]
I found [the issue](https://github.com/langchain-ai/langchain/issues/19211) and [the solution](https://github.com/langchain-ai/langchain/issues/19211#issuecomment-2036065038).

**Comment by hinthornw** [comment]
re: https://github.com/langchain-ai/langgraph/issues/78#issuecomment-1994836108

The reason explicit config passing is needed in python versions < 3.11 is that asyncio didn't add context support until 3.11

**Comment by eyurtsev** [comment]
Closing issue. You must either pass config explicitly when using python <3.11 or upgrade to python 3.11 starting from which we automatically do that on behalf of the user. 

The config object contains the callbacks which are necessary for astream events and astream log to get information about the streaming tokens from the llm!
